spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_ID}
    password: ${MYSQL_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect